### ISSUE TITLE
plugin: prepare a plugin template for dart

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clightning#36]

**Comment by vincenzopalazzo** [comment]
Here https://github.com/dart-lightning/dart_plugin

**Comment by swaptr** [comment]
I think we need to publish this library on https://pub.dev/ and continue with the template. :rocket:

**Comment by vincenzopalazzo** [comment]
Yeah! with a monorepo will be hard to import it with the git link!

But before working on the template, we need to complete the API!
